### ISSUE TITLE
能支持一下gitee吗

### ISSUE THREAD

**Issue by cayden-cheng** [DocsHome/spring-docs#2]

**Comment by jiachao23** [comment]
目前仅支持 GitHub，后续会考虑在 Gitee 和 GitHub同步更新。此项目已被迁移至 [jcohy-docs](https://github.com/jcohy/jcohy-docs)。在线阅读方式：[在线访问](https://www.jcohy.com/projects/spring-framework)。感谢您的关注

**Comment by cayden-cheng** [comment]
OK，感谢
